#!/usr/bin/env bash

alias ..='cd ..'
alias ...='cd ../../../'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gp="git add *;git commit -am save;git push;git status"
alias h="history"
alias hh=". $Etc/etc/h"
alias ls="ls -G"
alias tmux="tmux -f $Etc/etc/tmux-conf "
alias vi="vim -u $Etc/etc/vimrc "
alias vims="vim +PluginInstall +qall"         

doc() {
   cd $Etc/src
   for f in *.lua; do 
     g=$Etc/docs/${f%.lua}.md
     echo "# $g ..."
     cat $f | lua $Etc/etc/lua2md.lua $i > $g
   done
}

ok() {
   cd $Etc
   for i in *eg.lua; do 
     printf "\n###########################\n# $i\n"
     lua $i
   done
}

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🌙 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

tput bold; tput setaf 5
cat<<'EOF'
            _                        _             
           | |                      | |            
__  ___ __ | | __ _ _ __  _ __      | |_   _  __ _ 
\ \/ / '_ \| |/ _` | '_ \| '__|     | | | | |/ _` |
 >  <| |_) | | (_| | | | | |     _  | | |_| | (_| |
/_/\_\ .__/|_|\__,_|_| |_|_|    (_) |_|\__,_|\__,_|
     | |                                           
     |_|                                  

EOF
tput bold; tput setaf 241
echo "Short cuts:"
alias | sed 's/alias /  /'
tput sgr0
